apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-configmap
data:
  PORT: "8080"
  MONGODB_URI: "mongodb+srv://produser:6B3ZEqQj84sLo2TS@phonebazaar.jsbl0lm.mongodb.net/test?retryWrites=true&w=majority"
  AUTH_EMAIL: "phonebazaaar3@gmail.com"
  AUTH_PASS: "terx vbih jkiq kaqx"
  userTokenAuth: "a6167dd0943e9d04abcff46c8d5187b05201b4b297755b6768fd65bab7ba9f139a0b31d6b2c28b13933db72986ed1a60db580d2c389b4cca209bfdfebc42de7c"
  GOOGLE_CLIENT_ID: "969397154163-anm9i3bi48ejg202kp9ttcms3a8oege3.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  TWILIO_ACCOUNT_SID: "AC2082f1f26d8926e6ac10d691e5d553c4"
  TWILIO_AUTH_TOKEN: "c65fa964ab86f388ca2786f007f1af29"
  VERIFY_SID: "VA544b90725937c7eb79b913d3e378c833"
  KEY_SECRET: "2a0fS1LaXvhXY5lPQBpmbQC4"
  KEY_ID: "rzp_test_evMKTjM3ykRhMJ"